---

- name: "Update last operation"
  asb_last_operation:
    description: "0%: Starting"
  when: in_cluster

- name: 'Set facts'
  set_fact:
    cluster: '{{ "openshift" if "openshift" in lookup("k8s", cluster_info="version") else "kubernetes" }}'
    uniqname: '{{ _apb_service_instance_id.split("-")[0] | lower }}'

- name: "Set asterisk objects state={{ state }}"
  k8s:
    state: "{{ state }}"
    definition: "{{ lookup('template', item.name) | from_yaml }}"
  when: item.apply | default(True)
  loop:
    - name: configmap-env-config.yaml.j2
    - name: configmap-controller-config.yaml.j2
    - name: configmap-asterisk-vanilla.yaml.j2
    - name: configmap-controller-ui.yaml.j2
    - name: configmap-nginx-config.yaml.j2
    - name: pod-controller.yaml.j2
    - name: pod-etcd0.yaml.j2
    - name: pod-etcd1.yaml.j2
    - name: pod-etcd2.yaml.j2
    - name: pod-vnfui.yaml.j2
    - name: service-controller.yaml.j2
    - name: service-etcd0.yaml.j2
    - name: service-etcd1.yaml.j2
    - name: service-etcd2.yaml.j2
    - name: service-etcd-client.yaml.j2
    - name: service-vnfui.yaml.j2
    - name: deployment.yaml.j2

- name: "Update last operation"
  asb_last_operation:
    description: "100%: Done"
  when: in_cluster
